module: Gigya

include:
  - "**/Gigya/GigyaCore.swift"
  - "**/Network/Request/*.swift"
  - "**/Models/GigyaSocialProviders.swift"
  - "**/Models/User/GigyaAccount.swift"
  - "**/Global/Plugins/GigyaPluginEvent.swift"
  - "**/Global/Biometric/BiometricServiceProtocol.swift"
  - "**/Global/Resolvers/PendingRegistrationResolver.swift"
  - "**/Global/Resolvers/LinkAccountsResolver.swift"


copyright: 'Gigya © 2019.'

//swift_version: 5

theme: fullwidth
undocumented_text: ""

